let doctors = [
  {
    dName: "Khalid",
    dDegree: "Specialist",
    dRate: "4.5/5",
    sCost: "30$/session",
    dCatagory: "Neuropathology",
    workTime: ["7PM", "1AM"],
    appointments: [
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
    ],
  },
  {
    dName: "Seraj ben sasi",
    dDegree: "Consultant",
    dRate: "5/5",
    sCost: "35$/session",
    dCatagory: "Neuropathology",
    workTime: ["4PM", "10PM"],
    appointments: [
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
    ],
  },
  {
    dName: "Ahmed musa",
    dDegree: "Consultant",
    dRate: "4.5/5",
    sCost: "30$/session",
    dCatagory: "Neuropathology",
    workTime: ["8AM", "2PM"],
    appointments: [
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
    ],
  },
  {
    dName: "Marwan khalid",
    dDegree: "Professor",
    dRate: "5/5",
    sCost: "50$/session",
    dCatagory: "Neuropathology",
    workTime: ["11AM", "5PM"],
    appointments: [
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
    ],
  },
  {
    dName: "Yousef ibrahim",
    dDegree: "Senior specialist",
    dRate: "4/5",
    sCost: "30$/session",
    dCatagory: "Neuropathology",
    workTime: ["9AM", "3PM"],
    appointments: [
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
    ],
  },
  {
    dName: "Hanipal ahmed",
    dDegree: "Professor",
    dRate: "4/5",
    sCost: "40$/session",
    dCatagory: "Neuropathology",
    workTime: ["8AM", "2PM"],
    appointments: [
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
    ],
  },
  {
    dName: "Khalid deiaf",
    dDegree: "Specialist",
    dRate: "4.5/5",
    sCost: "30$/session",
    dCatagory: "Ear Therapy",
    workTime: ["7PM", "1AM"],
    appointments: [
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
    ],
  },
  {
    dName: "Seraj ben sasi",
    dDegree: "Consultant",
    dRate: "5/5",
    sCost: "35$/session",
    dCatagory: "Ear Therapy",
    workTime: ["4PM", "10PM"],
    appointments: [
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
    ],
  },
  {
    dName: "Ahmed musa",
    dDegree: "Consultant",
    dRate: "4.5/5",
    sCost: "30$/session",
    dCatagory: "Ear Therapy",
    workTime: ["8AM", "2PM"],
    appointments: [
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
    ],
  },
  {
    dName: "Marwan khalid",
    dDegree: "Professor",
    dRate: "5/5",
    sCost: "50$/session",
    dCatagory: "Ear Therapy",
    workTime: ["11AM", "5PM"],
    appointments: [
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
    ],
  },
  {
    dName: "Yousef ibrahim",
    dDegree: "Senior specialist",
    dRate: "4/5",
    sCost: "30$/session",
    dCatagory: "Ear Therapy",
    workTime: ["9AM", "3PM"],
    appointments: [
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
    ],
  },
  {
    dName: "Hanipal ahmed",
    dDegree: "Professor",
    dRate: "4/5",
    sCost: "40$/session",
    dCatagory: "Ear Therapy",
    workTime: ["8AM", "2PM"],
    appointments: [
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
    ],
  },

  {
    dName: "Khalid deiaf",
    dDegree: "Specialist",
    dRate: "4.5/5",
    sCost: "30$/session",
    dCatagory: "Eyesight Therapy",
    workTime: ["7PM", "1AM"],
    appointments: [
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
    ],
  },
  {
    dName: "Seraj ben sasi",
    dDegree: "Consultant",
    dRate: "5/5",
    sCost: "35$/session",
    dCatagory: "Eyesight Therapy",
    workTime: ["4PM", "10PM"],
    appointments: [
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
    ],
  },
  {
    dName: "Ahmed musa",
    dDegree: "Consultant",
    dRate: "4.5/5",
    sCost: "30$/session",
    dCatagory: "Eyesight Therapy",
    workTime: ["8AM", "2PM"],
    appointments: [
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
    ],
  },
  {
    dName: "Marwan khalid",
    dDegree: "Professor",
    dRate: "5/5",
    sCost: "50$/session",
    dCatagory: "Eyesight Therapy",
    workTime: ["11AM", "5PM"],
    appointments: [
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
    ],
  },
  {
    dName: "Yousef ibrahim",
    dDegree: "Senior specialist",
    dRate: "4/5",
    sCost: "30$/session",
    dCatagory: "Eyesight Therapy",
    workTime: ["9AM", "3PM"],
    appointments: [
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
    ],
  },
  {
    dName: "Hanipal ahmed",
    dDegree: "Professor",
    dRate: "4/5",
    sCost: "40$/session",
    dCatagory: "Eyesight Therapy",
    workTime: ["8AM", "2PM"],
    appointments: [
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
    ],
  },

  {
    dName: "Khalid deiaf",
    dDegree: "Specialist",
    dRate: "4.5/5",
    sCost: "30$/session",
    dCatagory: "Heart Therapy",
    workTime: ["7PM", "1AM"],
    appointments: [
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
    ],
  },
  {
    dName: "Seraj ben sasi",
    dDegree: "Consultant",
    dRate: "5/5",
    sCost: "35$/session",
    dCatagory: "Heart Therapy",
    workTime: ["4PM", "10PM"],
    appointments: [
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
    ],
  },
  {
    dName: "Ahmed musa",
    dDegree: "Consultant",
    dRate: "4.5/5",
    sCost: "30$/session",
    dCatagory: "Heart Therapy",
    workTime: ["8AM", "2PM"],
    appointments: [
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
    ],
  },
  {
    dName: "Marwan khalid",
    dDegree: "Professor",
    dRate: "5/5",
    sCost: "50$/session",
    dCatagory: "Heart Therapy",
    workTime: ["11AM", "5PM"],
    appointments: [
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
    ],
  },
  {
    dName: "Yousef ibrahim",
    dDegree: "Senior specialist",
    dRate: "4/5",
    sCost: "30$/session",
    dCatagory: "Heart Therapy",
    workTime: ["9AM", "3PM"],
    appointments: [
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
    ],
  },
  {
    dName: "Hanipal ahmed",
    dDegree: "Professor",
    dRate: "4/5",
    sCost: "40$/session",
    dCatagory: "Heart Therapy",
    workTime: ["8AM", "2PM"],
    appointments: [
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
    ],
  },

  {
    dName: "Khalid deiaf",
    dDegree: "Specialist",
    dRate: "4.5/5",
    sCost: "30$/session",
    dCatagory: "Gastro Enterology",
    workTime: ["7PM", "1AM"],
    appointments: [
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
    ],
  },
  {
    dName: "Seraj ben sasi",
    dDegree: "Consultant",
    dRate: "5/5",
    sCost: "35$/session",
    dCatagory: "Gastro Enterology",
    workTime: ["4PM", "10PM"],
    appointments: [
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
    ],
  },
  {
    dName: "Ahmed musa",
    dDegree: "Consultant",
    dRate: "4.5/5",
    sCost: "30$/session",
    dCatagory: "Gastro Enterology",
    workTime: ["8AM", "2PM"],
    appointments: [
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
    ],
  },
  {
    dName: "Marwan khalid",
    dDegree: "Professor",
    dRate: "5/5",
    sCost: "50$/session",
    dCatagory: "Gastro Enterology",
    workTime: ["11AM", "5PM"],
    appointments: [
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
    ],
  },
  {
    dName: "Yousef ibrahim",
    dDegree: "Senior specialist",
    dRate: "4/5",
    sCost: "30$/session",
    dCatagory: "Gastro Enterology",
    workTime: ["9AM", "3PM"],
    appointments: [
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
    ],
  },
  {
    dName: "Hanipal ahmed",
    dDegree: "Professor",
    dRate: "4/5",
    sCost: "40$/session",
    dCatagory: "Gastro Enterology",
    workTime: ["8AM", "2PM"],
    appointments: [
      {
        pName: "Mahmmoud khalid",
        pAge: 12,
        pGender: "Male",
        appointmentDate: "Thursday, April 3",
      },
      {
        pName: "Ibrahim ahmed",
        pAge: 18,
        pGender: "Male",
        appointmentDate: "Thursday, April 2",
      },
      {
        pName: "Ahmed ibrahim",
        pAge: 31,
        pGender: "Male",
        appointmentDate: "Thursday, April 1",
      },
      {
        pName: "Mia mohammed",
        pAge: 32,
        pGender: "Female",
        appointmentDate: "Thursday, April 12",
      },
      {
        pName: "Sarah ahmed",
        pAge: 25,
        pGender: "Female",
        appointmentDate: "Thursday, April 7",
      },
    ],
  },
];
